### ISSUE TITLE
Wallpaper acts like Schrodinger's cat

### ISSUE THREAD

**Issue by ShogunExecutioner** [y4my4my4m/kde-shader-wallpaper#11]
Commit `90ada4233e0c18d01e4706f0ad406116ba2230c0`

Wallpaper animation works normally while viewing any application in the foreground, but if you view desktop, it will stop, just like Schrodinger's cat :smile:

**Comment by y4my4my4m** [comment]
@ShogunExecutioner yeah, the pause on fullscreen is experimental...sometimes that same problem occurs to me but then it will stop happening if I deselect "pause on fullscreen" and reselect it.

Also it doesn't work with multi-monitors, as in, if you have shaderwallpaper on screen #1 but maximize an app on screen #2 it will stop the shaderwallpaper on screen #1 

Will keep working on it.

**Comment by win8linux** [comment]
Wouldn't a more reliable method be to detect when compositing is disabled by a fullscreen program (e.g. games) while it is running and pausing the wallpaper?

**Comment by y4my4my4m** [comment]
@win8linux should work (better) now.
