### ISSUE TITLE
Fix pause/resume for 2.0a and fullscreen

### ISSUE THREAD

**Issue by y4my4my4m** [y4my4my4m/kde-shader-wallpaper#17]
Accidentally broke it. Whoops :shushing_face:

**Comment by y4my4my4m** [comment]
https://github.com/y4my4my4m/kde-shader-wallpaper/pull/20 seems to fix the issue, huge thanks to @ja2142 for his contribution!

Closing this now.

**Comment by y4my4my4m** [comment]
Actually, seems that the "pause button" itself is broken now. That is because it uses the same flag as the fullscreen-pause while it should be a separate flag.

**Comment by y4my4my4m** [comment]
@Maxinova @unhappy-ending yes it's happening for Plasma6, probably will be there by friday.

**Comment by luisbocanegra** [comment]
Hi I have a similar feature in https://github.com/luisbocanegra/plasma-smart-video-wallpaper-reborn and it works really well https://github.com/luisbocanegra/plasma-smart-video-wallpaper-reborn/blob/main/package/contents/ui/WindowModel.qml not sure how much you need to access from TaskManager but maybe this project can benefit from that

**Comment by luisbocanegra** [comment]
Guess I can give a try to add it myself

**Comment by luisbocanegra** [comment]
It works 🎉

https://github.com/y4my4my4m/kde-shader-wallpaper/assets/15076387/bc1ea29c-9b31-4f76-9185-4de5d3deb4b0

I had to use `cfg_variableName` otherwise my pause mode combobox was reset to 0 after restarting plasma so clicking <kbd>Apply</kbd> is needed for this control now

**Comment by unhappy-ending** [comment]
That's awesome! I hope this gets merged :)

**Comment by y4my4my4m** [comment]
@luisbocanegra thanks for implementing this, i really appreciate it!
Guess I'll have to investigate `cfg_variableName` as well. I might need to start using that again instead of directly modifying the xml configuration variables

**Comment by luisbocanegra** [comment]
> @luisbocanegra thanks for implementing this, i really appreciate it! 

You're welcome!

> Guess I'll have to investigate `cfg_variableName` as well. I might need to start using that again instead of directly modifying the xml configuration variables

Yeah, the downside will be losing the ability to quickly review settings changes, not sure if directly applying and preserving the values can be done but I think it should be.

I think is a good idea to debug the direct `wallpaper.configuration.variableName` saving/reading to `~/.config/plasma-org.kde.plasma.desktop-appletsrc` `~/.config/kscreenlockerrc`, maybe something else is causing this saving problem and switching everything to cfg_ can be avoided?

**Comment by y4my4my4m** [comment]
@luisbocanegra 
> Yeah, the downside will be losing the ability to quickly review settings changes, not sure if directly applying and preserving the values can be done but I think it should be.

What i've hastly tried was simply apply both the value directly and applying it to `cfg_X` as well
https://github.com/y4my4my4m/kde-shader-wallpaper/issues/49

> I think is a good idea to debug the direct wallpaper.configuration.variableName saving/reading to ~/.config/plasma-org.kde.plasma.desktop-appletsrc ~/.config/kscreenlockerrc, maybe something else is causing this saving problem and switching everything to cfg_ can be avoided?

To be quite honest I'm not too sure how that even works, but so far I haven't encountered any major saving issues since implementing the cfg_
