### ISSUE TITLE
v2.0-alpha Does not run on it's own.

### ISSUE THREAD

**Issue by TriMoon** [y4my4my4m/kde-shader-wallpaper#21]
It stops when wallpaper config is not open/active.

**Comment by y4my4my4m** [comment]
@TriMoon i've just pulled @ja2142 's PR to master, it should resolve this now. 

Can you confirm? Thanks.

**Comment by TriMoon** [comment]
That version does not show-up when i try to install it via the desktop wallpapers interface, the latest it shows is still the v2.0-alpha.

**Comment by y4my4my4m** [comment]
Should be able to install directly from KDE now.

Works as expected.
Reopen if not.
