### ISSUE TITLE
Testing shaders on the AMD Vega8 GPU

### ISSUE THREAD

**Issue by danilw** [y4my4my4m/kde-shader-wallpaper#26]
**Tested on Ubuntu 20.10 Vega8 AMD Ryzen integrated GPU**, there are few problems with this GPU like - just launching `radeontop` make gpu freeze completely so some of the bugs with gpu/driver crash may come not from shaders/applications.
Tested using this Shader Wallpaper plugin in KDE.

**Suggestion - group shaders by _light gpu usage, medium gpu usage, high gpu usage_ in the UI of Shader Wallpaper option window.**

Result:
`no lag` - means shader work with 60fps
`30fps` - or less is shader has 100% gpu usage that makes whole system UI work at this framerate because shader
`0fps` - less than 1 frame per second

```
2D Clouds - no lag
Abstract Glassy_Field - 10-20fps
Abstract_Plane - 30fps
AlienVoxel - 1-5fps
Biomine - 10-20fps
Booting - no lag
Circuits - 10-20fps
Crazy Waves - no lag
Creation - no lag
Cylintrically Mapped Hexagon - 2-5fps
DNA tracer - 1fps
Day 79 - 5-10fps
Earthbound 1/2/3 - no lag
Electric Sinusiod - no lag
Fast Ocean - 0fps or gpu crash, black screen always instead of render
Fireworks - 0fps
Floating Color_Bubles - 5-10fps
Fovea - no lag
Fractal_Flythrough 20-30fps
Fractal_Tiling - no lag
Galaxy_Spirals - no lag
Geodesic_Tiling - 10-20fps

Gibson - 1-5fps
Grid_Landscape - no lag
HappyJumping - 1-2fps
Hyper_Tunnel - 1-2fps
Hyperspace_Travel - 5-10fps
Hypnoferromagnetism - 20-30fps
IO - 30fps
Impact - 60fps but does not work(black scren), may crash gpu
Infinite_Pinballs - 5fps
Invaders - no lag
Journey - 0fps but works (redner)
Kirby - 5-10fps
Laserworld - no lag
Linescape - 10-20fps
Luminescence - 1-5fps
Mandelbrot_Pattern_Decoration - 30-60fps
Matrix - no lag
Minkowski_Tube - no lag
Neon_Lit_Hexagons - 10-20fps
Noise_Fun - no lag
Noise_Watery - no lag
Oblivion_Radar - no lag

PS3_Menu - no lag
Perspex_Web_Lattice - 30fps
Pfhrector - no lag
Pixelated_RGB - no lag
Protean - 0fps
Radial_Blur_2k18 - 1-2fps
Raymarched_Reflections 30fps
Rorschach_Test - no lag
SIG2014 - no lag
Sanctuary - no lag
Satori - no lag
Seascape - 0fps
Seascape_Sailing - 20-30fps
Shiny_Circle - no lag
Shiny_Galaxy - 5-10fps
Ship_HUD - no lag
Simple - 60fps but black screen 
Snail - 0fps
Space_Curvature - 30fps
Spacebubbles - no lag
StarField_Practice - 30fps
Star_Nest - 30fps
Sunset_925 - no lag
Sunset_Cyber - no lag

SuperPlumber - no lag
Twisted_Columns - no lag
Twisted_Rings - 30fps
Vortex_Dust - 20-30fps
Voxel_Land_2 - no lag
Waves - no lag
Wavy_Background_Effect - no lag
Wolfenstein - no lag
Worms - 20-30fps

```

just updated with latest *30 shaders* update, shaders that missing:
```
Abstract_Terrain - 5-10fps
Cloud_Crystal - 30fps
Corridor_Travel - 20-30fps
Craziness - no lag
CubeLines - no lag
Curvature - 5-10fps
Day_74 - 10-20fps
Descent - 10-20fps
Descent3D - 30-60fps
Dez - 60fps but does not work(black screen)
Flow_Cells - no lag
FlyOnBuckaroo - 20-30fps
Glow_City - 10-20fps
Industry_II - no lag
LOVE - no lag
Liberation - 30fps
Midgar - 0fps
Mist 5-10fps
N64_Logo - 60fps but it just pink screen, does not work I think
Neon_Wires - 60fps but it just pink screen, does not work I think
OpArt_2 - no lag
PSX - 30fps
Paper_Kaleidoscope - 30fps
Patience_2 - 30fps
Reclaim_Streets - 0fps
Server_Room - 20-30fps
Sin_Wave - no lag
Stained_Lights - no lag
Torus_Thingy - 10-20fps
Triangle_Grid_Contouring - no lag
Voxel_Tunnel - no lag
Warping - 30fps
```

How I got fps numbers - I launch a simple window on top with fps counter, I used [my own app(example_minimal)](https://github.com/danilw/vulkan-shader-launcher/releases/tag/rel_1_1), a [screenshot with 30 fps](https://user-images.githubusercontent.com/24825887/116687611-22f08300-a9be-11eb-9a36-d878246a9400.png), the last number is fps, on the Cloud Crystal shader.

**Comment by y4my4my4m** [comment]
> N64_Logo - 60fps but it just pink screen, does not work I think

Works by unchecking GPL3 compatibility checkbox.

Thank you for this report, this is super useful and I will look into the two debug apps you've made.
I've been in the process of recreating kde-shader-wallpaper, i'm attempting to use kdevelop and C++ but i'm not sure yet which direction I will take. Regardless, there's a lot of work needed still on this wallpaper plugin.

> Suggestion - group shaders by light gpu usage, medium gpu usage, high gpu usage in the UI of Shader Wallpaper option window.

This is not a bad idea, or perhaps adding "tags" and descriptions and having a full list would be good.

Ultimately I want custom made shaders for the wallpaper plugin, with the option of downloading curated lists as extras.

**Comment by danilw** [comment]
> debug apps you've made.

That just my shader-related apps that have shader support, I use Ubuntu on different PC as testing for "Linux production" so I just download my apps that had fps counter that's all.

I think "perfect debug tool" to check shader performance - launch shaders in CPU on single CPU thread and look on few frames render time,  don't have setup for this or useful tips, developing a tool like this may take time...

The simple way to check shader performance on high-end videocards (Nvidia 1080 and better) - launch shader in fullscreen and use Nvidia XServer setting app or console tool `nvidia-smi -lms 100` [screenshot](https://user-images.githubusercontent.com/24825887/116778592-72e14f80-aa7b-11eb-88c4-4301c61c0c64.png), there displayed "GPU usage" and compare that usage to this my list, as an example for shaders that have 20-30fps on my list you got 20-40% GPU usage, for 0-10fps shaders in the list that be 80-90% GPU usage.
