### ISSUE TITLE
[Feature request] Ability to add a new wallpaper from shadertoy.com

### ISSUE THREAD

**Issue by ShogunExecutioner** [y4my4my4m/kde-shader-wallpaper#3]
First, thanks for making this lovely plugin.
If possible, please add a way to make user submit their shader code, or even a better way is to submit a url for target shadertoy.com and then the plugin fetches the code automatically.

**Comment by y4my4my4m** [comment]
@ShogunExecutioner it's in the plans! :+1: 

I've just now updated the plugin to v1.3, it's a bit easier to load custom shaders now using file dialog and a bunch of new ones have been added, but they still need to be "qml" embedded.

I'll get it to a point where you can load them directly from shadertoy or shader file.

**Comment by davidedmundson** [comment]
Something that will make your life easier:

At the moment you copy everything into a QML file exposed as a string property.
ShaderEffect can also take files to the fragmentShader

They have to be in the form file://full/path.frag  but you can use Qt.resolvedUrl for that

Then you can store fragment shaders directly as files and get rid of this QML factory.
It also supports a relevant QFileSelector tags so you can have different shaders for core profile

**Comment by y4my4my4m** [comment]
@davidedmundson thanks for the hint, i'll try it out
