### ISSUE TITLE
144 FPS?

### ISSUE THREAD

**Issue by Shroomerian** [y4my4my4m/kde-shader-wallpaper#32]
Hello. I have just a simple question and or feature request. Is it possible to have the shader wallpaper be active with a display which runs at 144 fps? Currently it definetly CAN run on a 144 display, but it does so with heavy lag tearing since the program is only running at 60 FPS.

https://user-images.githubusercontent.com/54857786/165340005-38882e15-af13-4e22-87fb-e31c5fef4612.mp4

This is what I see whenever I have the program running and I've set my display setting to run at 144 FPS. 

Thank you so much for reading! :D

**Comment by Shroomerian** [comment]
Ok, it seems that after a full on restart that the screen is behaving correctly now. I think this was purely on my side. Sorry for the trouble

**Comment by Shroomerian** [comment]
Ok, it seems that the issue reappeared after some sort of change. Also the stuttering seems to go away whenever I go into the Destkop and Wallpaper settings but reappear exactly as I close them.

**Comment by Shroomerian** [comment]
> Ok, it seems that the issue reappeared after some sort of change. Also the stuttering seems to go away whenever I go into the Destkop and Wallpaper settings but reappear exactly as I close them.

**Comment by y4my4my4m** [comment]
@Shroomerian 
I've dealt with this issue as well, I *believe* this is an artificial limit set in place by QML/KDE/Plasma's "shadereffect" built-in component.

https://doc.qt.io/qt-5/qml-qtquick-shadereffect.html
I've attempted to rewrite this entire plugin in Qt/C++ to circumvent this limit but alas, no luck.

It may be possible to lift the 60fps cap though, I just haven't found out how yet.

**Comment by y4my4my4m** [comment]
By the way, do you get the same stuttering with different shaders?

**Comment by Shroomerian** [comment]
> By the way, do you get the same stuttering with different shaders?

Yes, I did get the same kind of stuttering on the same shaders. But the curious thing is is that I've reinstalled the plugin, rebooted the computer and now the counter is displaying 144 fps correctly and the wallpaper no longer stutters.

https://user-images.githubusercontent.com/54857786/165547148-9d700df3-8ef2-47a0-98c4-0968309e996d.mp4

https://user-images.githubusercontent.com/54857786/165548051-c2b583f9-b8d1-428b-a83a-f4c7aaa183a6.mp4

I assume this has to be driver/system related, so if anything I think it's safe to close this issue down since I've seen nothing in the code which would indicate it has to do with the plugin.

Thank you for helping me and creating this awesome shader tool!

**Comment by y4my4my4m** [comment]
@Shroomerian 
Perhaps try this for debug purposes:

`pkill plasmashell` to kill your plasma process then launch it again from the terminal
`plasmashell`

you will see a bunch of warnings/info messages coming from the plugin.
There willl be many "shader restarted" messages and that is normal. However if you find other types of messages such as error or performance ones, it may help you figure out the stuttering issue.

**Comment by Shroomerian** [comment]
It seems that the issue was solved for me after switching from Manjaro KDE to OpenSuse KDE. It might have been some graphical drivers or packages interfering with the plasmashell.

There doesn't seem to be an issue on this side so I think closing the issue would be appropriate.
