### ISSUE TITLE
Mention AUR packages in README

### ISSUE THREAD

**Issue by Ashark** [y4my4my4m/kde-shader-wallpaper#37]
Hello. Thanks for this awesome project!

Can you mention installation from AUR packages for Arch Linux in Readme?
The packages are [plasma5-shader-wallpaper](https://aur.archlinux.org/packages/plasma5-shader-wallpaper) and [plasma5-shader-wallpaper-git](https://aur.archlinux.org/packages/plasma5-shader-wallpaper-git).

**Comment by y4my4my4m** [comment]
@Ashark oh wow, thanks for this! I didn't even know they were submitted to AUR packages.
Will update it!

**Comment by y4my4my4m** [comment]
https://github.com/y4my4my4m/kde-shader-wallpaper/commit/e4d57e98e2ccd4639fe05d8f0468ac884eae686a

Done, thank you! :)
