### ISSUE TITLE
Plasma 6 Compatibility

### ISSUE THREAD

**Issue by Anonymous4045** [y4my4my4m/kde-shader-wallpaper#38]
Are there plans to allow this to run on plasma 6? Is it  already able to? I couldn't see it in the wallpaper plugins.

**Comment by y4my4my4m** [comment]
@Anonymous4045 
Yes, I'm working on it right now actually.
They've changed many things with Plasma6 and I can only work on it via virtual machine so it's been slow. 

Sorry!
Will let you know when it's out.

**Comment by y4my4my4m** [comment]
@Anonymous4045
There's still a lot more to do, but I thought I'd share with you today's progress.

https://github.com/y4my4my4m/kde-shader-wallpaper/tree/plasma6

You can try it out now if you'd like (clone from this branch and install using kdepackage6 as per the readme)

There's only the waves and clouds shaders as of today. 
I will be porting more in the next few days.

**Comment by Anonymous4045** [comment]
@y4my4my4m thanks so much for continuing to work on it! The wave shader works great on my system, although there isn't an option in the wallpaper settings menu to change it. Great work so far!

**Comment by y4my4my4m** [comment]
@Anonymous4045 you can now change it.
I've added some more.
There's still a lot more to clean, they don't all work either.

More will be added in the next few days.

**Comment by y4my4my4m** [comment]
@Anonymous4045 
https://store.kde.org/p/2143912/
It's out! :)

Closing this.
Enjoy~

**Comment by PanoramicDawn** [comment]
I am having the same issue but only with the normal wallpaper and not the lockscreen now, on Plasma 6.2.5 on NixOS
