### ISSUE TITLE
Installation instructions

### ISSUE THREAD

**Issue by kzietek** [y4my4my4m/kde-shader-wallpaper#4]
It would be nice to have installation instructions in the readme.

**Comment by y4my4my4m** [comment]
@kzietek good idea! I will add it.

But you can install it easily if you right click on your desktop > configure desktop
Then in "Get New Plugins", it should be right there.

![image](https://user-images.githubusercontent.com/8145020/92334553-c1f1f480-f054-11ea-959d-1017fec92db4.png)

Simply click install for the latest version and should work right away :)

**Comment by y4my4my4m** [comment]
@kzietek 

Done: https://github.com/y4my4my4m/kde-shader-wallpaper/commit/c707599967cec552a917ab1df632c7474c7d38bd

Thanks for the feedback, make sure to rate on the KDE store! :)
https://store.kde.org/p/1413010/
