### ISSUE TITLE
How do I use this?

### ISSUE THREAD

**Issue by UnknownUser95** [y4my4my4m/kde-shader-wallpaper#40]
I have found your post on the KDE subreddit and it a go, however I only get a black screen.
The store description nor the README don't give any instructions or requirements either.

So I'm asking here:
Selecting a shader just gives me a black screen. The iChannels are unused (default state).
Are there any requirements for this (i.e. do I need an extra package)?
In your video I saw the iChannels being used. Are they important? What is their purpose for a shader? Are they required for shaders to work?

**Comment by jkerls** [comment]
You probably need to include QSB in your path as the readme mentions, grab the plasma6 specific release here, and on top of that he's got a case issue in the filenames. it couldn't find the PS3 shader because it was specified lower case but the file was capitalized.

Once I had my path set and made a copy with the right name it worked.

**Comment by jkerls** [comment]
That said, I don't know if there's a way to select which shader runs right now, short of only compiling the one you want; the UI is not currently in a functional state.

That's no knock - it looks like it'll be solid after an update, and the shader performance once I got it running was very reasonable.

I look forward to future releases.

**Comment by y4my4my4m** [comment]
@UnknownUser95 
Getting a black screen is not normal.
1. Did you install it from source or from the "Get new plugin" button in KDE wallpaper's plugin option?
2. What GPU are you using?

I've compiled the shaders using Vulkan-style for 100 es, 120 and 150, so it *should* work with most...

@jkerls 
You can select which shader actually, you right click on your desktop and configure it here:
![Screenshot 2024-04-04 134631](https://github.com/y4my4my4m/kde-shader-wallpaper/assets/8145020/184b8af6-a1f7-4d10-8048-ce0bdd00e3c9)

![Screenshot 2024-04-04 134611](https://github.com/y4my4my4m/kde-shader-wallpaper/assets/8145020/c1a19040-226d-43e1-9b96-4d628def4267)


I've heard Plasma6 added an option for wallpapers in System Settings though and I don't think it shows up right now, I will be adding that function too if possible.

**Comment by y4my4my4m** [comment]
> You probably need to include QSB in your path as the readme mentions, grab the plasma6 specific release here, and on top of that he's got a case issue in the filenames. it couldn't find the PS3 shader because it was specified lower case but the file was capitalized.
> 
> Once I had my path set and made a copy with the right name it worked.

Thanks for that, I will fix it

**Comment by y4my4my4m** [comment]
@UnknownUser95 
Just for clarity's sake,

iChannels are important for some shaders, it's a case-by-base basis depending on the shader.
Some shader requires to be passed an image, for example, receiving noise input via a noise texture/image.
Others don't.

For example, [Rainier Mood](https://github.com/y4my4my4m/kde-shader-wallpaper/blob/plasma6/package/contents/ui/Shaders6/Rainier_Mood.frag.qsb) uses iChannel0 as a background image (so just choose a wallpaper image you'd like) and you'll get a nice rain effect on top.

**Comment by jkerls** [comment]
Okay, but closing and re-opening did seem to apply one. I'll have to experiment.

**Comment by y4my4my4m** [comment]
> @y4my4my4m Yeah, I have that dropdown, but it doesn't actually select anything, it runs the ps3menu shader no matter what. And no change to anything on that page ever makes the Apply button light up.

Strange...
The PS3 one *is* the [default one](https://github.com/y4my4my4m/kde-shader-wallpaper/blob/e1a7cd922a356207ae6d47512f9946be5b82f007/package/contents/config/main.xml#L10) indeed.
It means that somehow that value couldn't be written to when selecting another shader? 🤔

**Comment by y4my4my4m** [comment]
I've updated the release package to account for that (both KDE store and github), please reinstall if you run into a problem again.

**Comment by UnknownUser95** [comment]
> @UnknownUser95 
> Getting a black screen is not normal.
> 1. Did you install it from source or from the "Get new plugin" button in KDE wallpaper's plugin option?
> 2. What GPU are you using?
> 
> I've compiled the shaders using Vulkan-style for 100 es, 120 and 150, so it *should* work with most...
> 
> @jkerls 
> You can select which shader actually, you right click on your desktop and configure it here:
> ![Screenshot 2024-04-04 134631](https://github.com/y4my4my4m/kde-shader-wallpaper/assets/8145020/184b8af6-a1f7-4d10-8048-ce0bdd00e3c9)
> 
> ![Screenshot 2024-04-04 134611](https://github.com/y4my4my4m/kde-shader-wallpaper/assets/8145020/c1a19040-226d-43e1-9b96-4d628def4267)
> 
> 
> I've heard Plasma6 added an option for wallpapers in System Settings though and I don't think it shows up right now, I will be adding that function too if possible.

1. I got it from the KDE store.
2. A RX 6900 XT.

**Comment by UnknownUser95** [comment]
> I've updated the release package to account for that (both KDE store and github), please reinstall if you run into a problem again.
> 
> Edit: Also, I've tried from Settings > Wallpaper. It doesn't work, you have to do it from right clicking your desktop.
> 
> I will update it.

I now had the time to check if the update works and yes, it does!

**Comment by UnknownUser95** [comment]
> @UnknownUser95 Just for clarity's sake,
> 
> iChannels are important for some shaders, it's a case-by-base basis depending on the shader. Some shader requires to be passed an image, for example, receiving noise input via a noise texture/image. Others don't.
> 
> For example, [Rainier Mood](https://github.com/y4my4my4m/kde-shader-wallpaper/blob/plasma6/package/contents/ui/Shaders6/Rainier_Mood.frag.qsb) uses iChannel0 as a background image (so just choose a wallpaper image you'd like) and you'll get a nice rain effect on top.

Completely forget to say thank you for the clarification!
