### ISSUE TITLE
In Plasma 6 Edition changes does not work

### ISSUE THREAD

**Issue by worthymelight** [y4my4my4m/kde-shader-wallpaper#42]
In Plasma 6 Edition changes does not work

**Comment by y4my4my4m** [comment]
@worthymelight which changes?
What do you mean?

**Comment by VolBournz** [comment]
The changes you make don't take effect.
It's always the same wallpaper. 

Some relevant info that might be useful.
![image](https://github.com/y4my4my4m/kde-shader-wallpaper/assets/17241246/3b029d6d-8b60-4d95-8219-8f4026aa8162)

https://github.com/y4my4my4m/kde-shader-wallpaper/assets/17241246/dd71478a-7d65-4f18-b38f-0d922cd4f37a

**Comment by Maticzpl** [comment]
Reopening the wallpaper settings after setting type to shader does fix this for me

**Comment by y4my4my4m** [comment]
There was an issue, the default config's shader had a filename mismatch.

I've updated it, just reinstall the plugin please.

If not, please try to set it from the desktop, not the settings>wallpaper menu. Unfortunately you can't set it from that menu yet.

**Comment by luisbocanegra** [comment]
I suspect the root cause of settings sometimes not saving could be that this plugin writes `wallpaper.configuration.variableName` directly and Plasma doesn't like that? 🤔
