### ISSUE TITLE
Abstract_Liquid by SentientCymatic

### ISSUE THREAD

**Issue by unhappy-ending** [y4my4my4m/kde-shader-wallpaper#45]
I modified this from the original is this line to have a zoom that fit a my screen a little better. This way it doesn't have a repetitive pattern across the screen.

Default is:
`    float iSmoke = 0.01;`

vs

`    float iSmoke = 0.005;`

Otherwise, only added in the code bits for manual frag > qsb compilation.

[Abstract_Liquid.frag.tar.gz](https://github.com/y4my4my4m/kde-shader-wallpaper/files/14877314/Abstract_Liquid.frag.tar.gz)

**Comment by y4my4my4m** [comment]
Thanks! I'll check and add it!
