### ISSUE TITLE
Crashes my PC

### ISSUE THREAD

**Issue by SuperBoyne** [y4my4my4m/kde-shader-wallpaper#8]
When I activated it and picked one, my PC froze, and the screen turned black except for my cursor. I can press the power button, log out and go back to the desktop, but I only have seconds before it crashes again.

**Comment by y4my4my4m** [comment]
@SuperBoyne 

That's no good.
Have you tried activating the GLS3 compatibility option?

Could you share your specs?

Also if you need to remove it, delete the folder in:
`sudo rm -rf ~/.local/share/plasma/wallpaper/online.knowmad.shaderwallpaper`

**Comment by SuperBoyne** [comment]
I already reinstalled Kubuntu lol.
My graphics card is literally crap.
Should have waited lol.
It was a new install.
